project_name: terradrift
builds:
  - id: terradrift-server
    main: ./terradrift-server
    binary: terradrift-server
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: terradrift-cli
    main: ./terradrift-cli
    binary: terradrift-cli
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
- image_templates: 
  - "docker.io/rootsami/terradrift:{{ .Version }}"
  - "docker.io/rootsami/terradrift:latest"
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/rootsami/terradrift
  - --label=org.opencontainers.image.source=https://github.com/rootsami/terradrift
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
